name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
          # Your workflow steps here

          - name: Checkout Repository
            uses: actions/checkout@v2
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
          
          - name: Build Frontend Docker Image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mearn-stack_frontend mern-docker/frontend
          
          - name: Build Backend Docker Image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mearn-stack_backend mern-docker/backend

          - name: Build appaew Docker Image
            run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mearn-stack_appew react-docker
          
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          
          - name: Push Frontend Docker Image
            run: docker push stt96/mearn-stack_frontend:latest
          
          - name: Push Backend Docker Image
            run: docker push stt96/mearn-stack_backend:latest
          - name: Push appew Docker Image
            run: docker push stt96/mearn-stack_appew:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

          - name: SSH into Server instance and deploy
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                port: ${{ secrets.SERVER_PORT }}
                
                script: |
                  docker stop mearn-stack_frontend || true
                  docker rm -f mearn-stack_frontend || true
                  docker stop mearn-stack_backend || true
                  docker rm -f mearn-stack_backend || true
                  docker stop mearn-stack_appew || true
                  docker rm -f mearn-stack_appew || true
                  # pull images from Docker Hub
                  docker pull stt96/mearn-stack_appew:latest
                  docker pull stt96/mearn-stack_frontend:latest
                  docker pull stt96/mearn-stack_backend:latest

                 
                  
                  docker system prune -f

                  docker run -d -p 5174:4000 --name mearn-stack_appew ${{ secrets.DOCKER_USERNAME }}/mearn-stack_appew:latest
                  #5174 is the port of machine 4000 is the port of container
                  docker run -d -p 8000:8000 --name mearn-stack_backend ${{ secrets.DOCKER_USERNAME }}/mearn-stack_backend:latest
                  docker run -d -p 5173:5173 --name mearn-stack_frontend ${{ secrets.DOCKER_USERNAME }}/mearn-stack_frontend:latest
